[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "cd src/backend && gunicorn app:app --bind 0.0.0.0:$PORT"
restartPolicyType = "on_failure"

[env]
PORT = "8081"
